#include "cpu.h"
#include "generated_aliases.h"
#include "helper.h"
#include <assert.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>

int default_decoder_handler(
    rv64_instruction_t /*unused*/,
    void *_Nullable *_Nonnull /*unused*/,
    uint7b_t /*unused*/,
    void (*_Nullable *_Nonnull /*unused*/)(
        struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins))
{
    return ENOTSUP;
}

int (*ins_decode_handlers[UINT7B_MAX + 1])(
    rv64_instruction_t ins,
    void *_Nullable *_Nonnull ret_decoded,
    uint7b_t opcode,
    void (*_Nullable *_Nonnull ret_execution_handler)(
        struct rv64_cpu *_Nonnull cpu,
        void *_Nonnull *_Nonnull vdecoded_ins)) = {
    [0 ... UINT7B_MAX - 1] = default_decoder_handler};

void (*_Nonnull execution_handlers[OPCODE_MAX + 1][FUNC3_MAX + 1]
                                  [FUNC7_MAX + 1])(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins);

void illegal_instruction_handler(
    struct rv64_cpu *_Nonnull /*unused*/, void *_Nonnull *_Nonnull /*unused*/)
{
    puts("hit an illegal instruction: TODO: handle exceptions");
}

void __attribute__((constructor())) init_ins_decode_handlers(void)
{
    ins_decode_handlers[LOAD]      = decode_ins_i;
    ins_decode_handlers[STORE]     = decode_ins_s;
    ins_decode_handlers[OP_IMM]    = decode_ins_i;
    ins_decode_handlers[LUI]       = decode_ins_u;
    ins_decode_handlers[OP]        = decode_ins_r;
    ins_decode_handlers[JAL]       = decode_ins_j;
    ins_decode_handlers[JALR]      = decode_ins_i;
    ins_decode_handlers[MISC_MEM]  = decode_ins_i;
    ins_decode_handlers[SYSTEM]    = decode_ins_i;
    ins_decode_handlers[OP_IMM_32] = decode_ins_i;
    ins_decode_handlers[AUIPC]     = decode_ins_u;
    ins_decode_handlers[OP_32]     = decode_ins_r;
}

void __attribute__((constructor())) init_execution_handlers(void)
{
    fill_execution_handler_with_default_handler();
    // the following registration of handlers is generated by notebooklm, with some editing

    int func3      = 0;
    int func7      = 0;
    uint8_t opcode = 0;

    // -------------------------------------------------------------------------
    // LUI, AUIPC, JAL (U-Type & J-Type: No func3, No func7)
    // -------------------------------------------------------------------------
    register_execution_handler(LUI, NULL, NULL, execute_lui);
    register_execution_handler(AUIPC, NULL, NULL, execute_auipc);
    register_execution_handler(JAL, NULL, NULL, execute_jal);

    // -------------------------------------------------------------------------
    // JALR (I-Type)
    // -------------------------------------------------------------------------
    func3 = JALR_FUNC3;
    register_execution_handler(JALR, NULL, &func3, execute_jalr);

    // -------------------------------------------------------------------------
    // BRANCH (B-Type)
    // -------------------------------------------------------------------------
    func3 = BEQ_FUNC3;
    register_execution_handler(BRANCH, NULL, &func3, execute_beq);
    func3 = BNE_FUNC3;
    register_execution_handler(BRANCH, NULL, &func3, execute_bne);
    func3 = BLT_FUNC3;
    register_execution_handler(BRANCH, NULL, &func3, execute_blt);
    func3 = BGE_FUNC3;
    register_execution_handler(BRANCH, NULL, &func3, execute_bge);
    func3 = BLTU_FUNC3;
    register_execution_handler(BRANCH, NULL, &func3, execute_bltu);
    func3 = BGEU_FUNC3;
    register_execution_handler(BRANCH, NULL, &func3, execute_bgeu);

    // TODO:
    // -------------------------------------------------------------------------
    // LOAD (I-Type)
    // -------------------------------------------------------------------------
    // func3 = LB_FUNC3;  register_execution_handler(LOAD, NULL, &func3, execute_lb);
    // func3 = LH_FUNC3;  register_execution_handler(LOAD, NULL, &func3, execute_lh);
    // func3 = LW_FUNC3;  register_execution_handler(LOAD, NULL, &func3, execute_lw);
    // func3 = LD_FUNC3;  register_execution_handler(LOAD, NULL, &func3, execute_ld);
    // func3 = LBU_FUNC3; register_execution_handler(LOAD, NULL, &func3, execute_lbu);
    // func3 = LHU_FUNC3; register_execution_handler(LOAD, NULL, &func3, execute_lhu);
    // func3 = LWU_FUNC3; register_execution_handler(LOAD, NULL, &func3, execute_lwu);

    // TODO:
    // -------------------------------------------------------------------------
    // STORE (S-Type)
    // -------------------------------------------------------------------------
    // func3 = SB_FUNC3; register_execution_handler(STORE, NULL, &func3, execute_sb);
    // func3 = SH_FUNC3; register_execution_handler(STORE, NULL, &func3, execute_sh);
    // func3 = SW_FUNC3; register_execution_handler(STORE, NULL, &func3, execute_sw);
    // func3 = SD_FUNC3; register_execution_handler(STORE, NULL, &func3, execute_sd);

    // -------------------------------------------------------------------------
    // OP-IMM (I-Type Immediate Arithmetic & Shifts)
    // -------------------------------------------------------------------------
    func3 = ADDI_FUNC3;
    register_execution_handler(OP_IMM, NULL, &func3, execute_addi);
    func3 = SLTI_FUNC3;
    register_execution_handler(OP_IMM, NULL, &func3, execute_slti);
    func3 = SLTIU_FUNC3;
    register_execution_handler(OP_IMM, NULL, &func3, execute_sltiu);
    func3 = XORI_FUNC3;
    register_execution_handler(OP_IMM, NULL, &func3, execute_xori);
    func3 = ORI_FUNC3;
    register_execution_handler(OP_IMM, NULL, &func3, execute_ori);
    func3 = ANDI_FUNC3;
    register_execution_handler(OP_IMM, NULL, &func3, execute_andi);

    func3 = SLLI_FUNC3;
    func7 = SLLI_FUNC7;
    register_execution_handler(OP_IMM, &func7, &func3, execute_slli);
    func3 = SRLI_FUNC3;
    func7 = SRLI_FUNC7;
    register_execution_handler(OP_IMM, &func7, &func3, execute_srlai);
    func3 = SRAI_FUNC3;
    func7 = SRAI_FUNC7;
    register_execution_handler(OP_IMM, &func7, &func3, execute_srlai);

    // -------------------------------------------------------------------------
    // OP-IMM-32 (I-Type 32-bit Word Operations - RV64I)
    // -------------------------------------------------------------------------
    func3 = ADDIW_FUNC3;
    register_execution_handler(OP_IMM_32, NULL, &func3, execute_addiw);

    func3 = SLLIW_FUNC3;
    func7 = SLLIW_FUNC7;
    register_execution_handler(OP_IMM_32, &func7, &func3, execute_slliw);
    func3 = SRLIW_FUNC3;
    func7 = SRLIW_FUNC7;
    register_execution_handler(OP_IMM_32, &func7, &func3, execute_srlaiw);
    func3 = SRAIW_FUNC3;
    func7 = SRAIW_FUNC7;
    register_execution_handler(OP_IMM_32, &func7, &func3, execute_srlaiw);

    // -------------------------------------------------------------------------
    // OP (R-Type Register-Register Operations + RV32M/RV64M)
    // -------------------------------------------------------------------------
    func3 = ADD_FUNC3;
    func7 = ADD_FUNC7;
    register_execution_handler(OP, &func7, &func3, execute_add);
    func3 = SUB_FUNC3;
    func7 = SUB_FUNC7;
    register_execution_handler(OP, &func7, &func3, execute_sub);
    func3 = SLL_FUNC3;
    func7 = SLL_FUNC7;
    register_execution_handler(OP, &func7, &func3, execute_sll);
    func3 = SLT_FUNC3;
    func7 = SLT_FUNC7;
    register_execution_handler(OP, &func7, &func3, execute_slt);
    func3 = SLTU_FUNC3;
    func7 = SLTU_FUNC7;
    register_execution_handler(OP, &func7, &func3, execute_sltu);
    func3 = XOR_FUNC3;
    func7 = XOR_FUNC7;
    register_execution_handler(OP, &func7, &func3, execute_xor);
    func3 = SRL_FUNC3;
    func7 = SRL_FUNC7;
    register_execution_handler(OP, &func7, &func3, execute_srla);
    func3 = SRA_FUNC3;
    func7 = SRA_FUNC7;
    register_execution_handler(OP, &func7, &func3, execute_srla);
    func3 = OR_FUNC3;
    func7 = OR_FUNC7;
    register_execution_handler(OP, &func7, &func3, execute_or);
    func3 = AND_FUNC3;
    func7 = AND_FUNC7;
    register_execution_handler(OP, &func7, &func3, execute_and);

    // TODO:
    // RV32M / RV64M Extension
    // func3 = MUL_FUNC3;    func7 = MUL_FUNC7;    register_execution_handler(OP, &func7, &func3, execute_mul);
    // func3 = MULH_FUNC3;   func7 = MULH_FUNC7;   register_execution_handler(OP, &func7, &func3, execute_mulh);
    // func3 = MULHSU_FUNC3; func7 = MULHSU_FUNC7; register_execution_handler(OP, &func7, &func3, execute_mulhsu);
    // func3 = MULHU_FUNC3;  func7 = MULHU_FUNC7;  register_execution_handler(OP, &func7, &func3, execute_mulhu);
    // func3 = DIV_FUNC3;    func7 = DIV_FUNC7;    register_execution_handler(OP, &func7, &func3, execute_div);
    // func3 = DIVU_FUNC3;   func7 = DIVU_FUNC7;   register_execution_handler(OP, &func7, &func3, execute_divu);
    // func3 = REM_FUNC3;    func7 = REM_FUNC7;    register_execution_handler(OP, &func7, &func3, execute_rem);
    // func3 = REMU_FUNC3;   func7 = REMU_FUNC7;   register_execution_handler(OP, &func7, &func3, execute_remu);

    // -------------------------------------------------------------------------
    // OP-32 (R-Type 32-bit Word Operations + RV64M - RV64I)
    // -------------------------------------------------------------------------
    func3 = ADDW_FUNC3;
    func7 = ADDW_FUNC7;
    register_execution_handler(OP_32, &func7, &func3, execute_addw);
    func3 = SUBW_FUNC3;
    func7 = SUBW_FUNC7;
    register_execution_handler(OP_32, &func7, &func3, execute_subw);
    func3 = SLLW_FUNC3;
    func7 = SLLW_FUNC7;
    register_execution_handler(OP_32, &func7, &func3, execute_sllw);
    func3 = SRLW_FUNC3;
    func7 = SRLW_FUNC7;
    register_execution_handler(OP_32, &func7, &func3, execute_srlaw);
    func3 = SRAW_FUNC3;
    func7 = SRAW_FUNC7;
    register_execution_handler(OP_32, &func7, &func3, execute_srlaw);

    // TODO:
    // RV64M Extension Word Variants
    // func3 = MULW_FUNC3;  func7 = MULW_FUNC7;  register_execution_handler(OP_32, &func7, &func3, execute_mulw);
    // func3 = DIVW_FUNC3;  func7 = DIVW_FUNC7;  register_execution_handler(OP_32, &func7, &func3, execute_divw);
    // func3 = DIVUW_FUNC3; func7 = DIVUW_FUNC7; register_execution_handler(OP_32, &func7, &func3, execute_divuw);
    // func3 = REMW_FUNC3;  func7 = REMW_FUNC7;  register_execution_handler(OP_32, &func7, &func3, execute_remw);
    // func3 = REMUW_FUNC3; func7 = REMUW_FUNC7; register_execution_handler(OP_32, &func7, &func3, execute_remuw);

    // TODO:
    // -------------------------------------------------------------------------
    // MISC-MEM (FENCE & FENCE.I)
    // -------------------------------------------------------------------------
    // func3 = FENCE_FUNC3;   register_execution_handler(MISC_MEM, NULL, &func3, execute_fence);
    // func3 = FENCE_I_FUNC3; register_execution_handler(MISC_MEM, NULL, &func3, execute_fence_i);

    // TODO:
    // -------------------------------------------------------------------------
    // SYSTEM (ECALL, EBREAK, Zicsr)
    // Note: ECALL & EBREAK share func3 = 0; inside execute_system(), inspect imm[11:0]
    // -------------------------------------------------------------------------
    // func3 = ECALL_FUNC3; register_execution_handler(SYSTEM, NULL, &func3, execute_system);
    //
    // func3 = CSRRW_FUNC3;  register_execution_handler(SYSTEM, NULL, &func3, execute_csrrw);
    // func3 = CSRRS_FUNC3;  register_execution_handler(SYSTEM, NULL, &func3, execute_csrrs);
    // func3 = CSRRC_FUNC3;  register_execution_handler(SYSTEM, NULL, &func3, execute_csrrc);
    // func3 = CSRRWI_FUNC3; register_execution_handler(SYSTEM, NULL, &func3, execute_csrrwi);
    // func3 = CSRRSI_FUNC3; register_execution_handler(SYSTEM, NULL, &func3, execute_csrrsi);
    // func3 = CSRRCI_FUNC3; register_execution_handler(SYSTEM, NULL, &func3, execute_csrrci);
}

uint64_t decode_imm_i(rv64_instruction_t ins)
{
    uint64_t ret     = 0;
    uint8_t sign_bit = ins >> (RV64_INS_LEN - 1);

    ret = ins >> 20;

    ret = repeat_bit_in_num(ret, IMM_I_SIZE_BITS, sign_bit);

    return ret;
}

static const uint8_t s_imm1_size_bits = 5;
static const uint8_t s_imm1_bitpos    = 7;

static const uint8_t s_imm2_size_bits = 7;
static const uint8_t s_imm2_bitpos    = 25;
uint64_t decode_imm_s(rv64_instruction_t ins)
{
    const uint64_t s_imm1_bitmask = bitmask_from_bit_size(s_imm1_size_bits);
    const uint64_t s_imm2_bitmask = bitmask_from_bit_size(s_imm2_size_bits);
    uint64_t ret                  = 0;
    uint8_t sign_bit              = ins >> (RV64_INS_LEN - 1);
    uint64_t imm1 =
        extract_bits_from_uint64(ins, s_imm1_bitpos, s_imm1_bitmask);
    uint64_t imm2 =
        extract_bits_from_uint64(ins, s_imm2_bitpos, s_imm2_bitmask);

    ret = imm1 + (imm2 << s_imm1_size_bits);

    ret = repeat_bit_in_num(ret, IMM_I_SIZE_BITS, sign_bit);

    return ret;
}

static const uint8_t b_imm1_size_bits      = 1;
static const uint8_t b_imm1_encoded_bitpos = 7;
static const uint8_t b_imm1_real_bitpos    = 11;

static const uint8_t b_imm2_size_bits      = 4;
static const uint8_t b_imm2_encoded_bitpos = 8;
static const uint8_t b_imm2_real_bitpos    = 1;

static const uint8_t b_imm3_size_bits      = 6;
static const uint8_t b_imm3_encoded_bitpos = 25;
static const uint8_t b_imm3_real_bitpos    = 5;

static const uint8_t b_imm4_size_bits      = 1;
static const uint8_t b_imm4_encoded_bitpos = 31;
static const uint8_t b_imm4_real_bitpos    = 12;
uint64_t decode_imm_b(rv64_instruction_t ins)
{
    const uint64_t b_imm1_bitmask = bitmask_from_bit_size(b_imm1_size_bits);
    const uint64_t b_imm2_bitmask = bitmask_from_bit_size(b_imm2_size_bits);
    const uint64_t b_imm3_bitmask = bitmask_from_bit_size(b_imm3_size_bits);
    const uint64_t b_imm4_bitmask = bitmask_from_bit_size(b_imm4_size_bits);

    uint64_t ret     = 0;
    uint8_t sign_bit = ins >> (RV64_INS_LEN - 1);

    uint64_t imm1 =
        extract_bits_from_uint64(ins, b_imm1_encoded_bitpos, b_imm1_bitmask);
    uint64_t imm2 =
        extract_bits_from_uint64(ins, b_imm2_encoded_bitpos, b_imm2_bitmask);
    uint64_t imm3 =
        extract_bits_from_uint64(ins, b_imm3_encoded_bitpos, b_imm3_bitmask);
    uint64_t imm4 =
        extract_bits_from_uint64(ins, b_imm4_encoded_bitpos, b_imm4_bitmask);

    ret = (imm1 << b_imm1_real_bitpos) + (imm2 << b_imm2_real_bitpos) +
          (imm3 << b_imm3_real_bitpos) + (imm4 << b_imm4_real_bitpos);

    ret = repeat_bit_in_num(ret, IMM_B_SIZE_BITS, sign_bit);

    return ret;
}

static const uint8_t u_imm1_size_bits      = 20;
static const uint8_t u_imm1_encoded_bitpos = 12;
static const uint8_t u_imm1_real_bitpos    = 12;
uint64_t decode_imm_u(rv64_instruction_t ins)
{
    const uint64_t u_imm1_bitmask = bitmask_from_bit_size(u_imm1_size_bits);

    uint64_t ret = 0;

    uint64_t imm1 =
        extract_bits_from_uint64(ins, u_imm1_encoded_bitpos, u_imm1_bitmask);

    ret = (imm1 << u_imm1_real_bitpos);

    return ret;
}

static const uint8_t j_imm1_size_bits      = 8;
static const uint8_t j_imm1_encoded_bitpos = 12;
static const uint8_t j_imm1_real_bitpos    = 12;

static const uint8_t j_imm2_size_bits      = 1;
static const uint8_t j_imm2_encoded_bitpos = 20;
static const uint8_t j_imm2_real_bitpos    = 11;

static const uint8_t j_imm3_size_bits      = 10;
static const uint8_t j_imm3_encoded_bitpos = 21;
static const uint8_t j_imm3_real_bitpos    = 1;

static const uint8_t j_imm4_size_bits      = 1;
static const uint8_t j_imm4_encoded_bitpos = 31;
static const uint8_t j_imm4_real_bitpos    = 20;
uint64_t decode_imm_j(rv64_instruction_t ins)
{
    const uint64_t j_imm1_bitmask = bitmask_from_bit_size(j_imm1_size_bits);
    const uint64_t j_imm2_bitmask = bitmask_from_bit_size(j_imm2_size_bits);
    const uint64_t j_imm3_bitmask = bitmask_from_bit_size(j_imm3_size_bits);
    const uint64_t j_imm4_bitmask = bitmask_from_bit_size(j_imm4_size_bits);

    uint64_t ret     = 0;
    uint8_t sign_bit = ins >> (RV64_INS_LEN - 1);

    uint64_t imm1 =
        extract_bits_from_uint64(ins, j_imm1_encoded_bitpos, j_imm1_bitmask);
    uint64_t imm2 =
        extract_bits_from_uint64(ins, j_imm2_encoded_bitpos, j_imm2_bitmask);
    uint64_t imm3 =
        extract_bits_from_uint64(ins, j_imm3_encoded_bitpos, j_imm3_bitmask);
    uint64_t imm4 =
        extract_bits_from_uint64(ins, j_imm4_encoded_bitpos, j_imm4_bitmask);

    ret = (imm1 << j_imm1_real_bitpos) + (imm2 << j_imm2_real_bitpos) +
          (imm3 << j_imm3_real_bitpos) + (imm4 << j_imm4_real_bitpos);

    ret = repeat_bit_in_num(ret, IMM_J_SIZE_BITS, sign_bit);

    return ret;
}

const uint64_t rd_ind_size_bits  = 5;
const uint64_t rd_encoded_bitpos = 7;
uint5b_t decode_rd(rv64_instruction_t ins)
{
    uint64_t bitmask = bitmask_from_bit_size(rd_ind_size_bits);
    return extract_bits_from_uint64(ins, rd_encoded_bitpos, bitmask);
}

const uint64_t rs1_ind_size_bits  = 5;
const uint64_t rs1_encoded_bitpos = 15;
uint5b_t decode_rs1(rv64_instruction_t ins)
{
    uint64_t bitmask = bitmask_from_bit_size(rs1_ind_size_bits);
    return extract_bits_from_uint64(ins, rs1_encoded_bitpos, bitmask);
}

const uint64_t rs2_ind_size_bits  = 5;
const uint64_t rs2_encoded_bitpos = 20;
uint5b_t decode_rs2(rv64_instruction_t ins)
{
    uint64_t bitmask = bitmask_from_bit_size(rs2_ind_size_bits);
    return extract_bits_from_uint64(ins, rs2_encoded_bitpos, bitmask);
}

const uint64_t func3_size_bits       = 3;
const uint64_t func3_encoded_bit_pos = 12;
uint3b_t decode_func3(rv64_instruction_t ins)
{
    uint64_t bitmask = bitmask_from_bit_size(func3_size_bits);
    return extract_bits_from_uint64(ins, func3_encoded_bit_pos, bitmask);
}

const uint64_t func7_size_bits       = 7;
const uint64_t func7_encoded_bit_pos = 25;
uint3b_t decode_func7(rv64_instruction_t ins)
{
    uint64_t bitmask = bitmask_from_bit_size(func7_size_bits);
    return extract_bits_from_uint64(ins, func7_encoded_bit_pos, bitmask);
}

const uint64_t opcode_size_bits       = 7;
const uint64_t opcode_encoded_bit_pos = 0;
uint8_t decode_opcode(rv64_instruction_t ins)
{
    uint64_t bitmask = bitmask_from_bit_size(opcode_size_bits);
    return extract_bits_from_uint64(ins, opcode_encoded_bit_pos, bitmask);
}

int decode_ins_r(
    rv64_instruction_t ins,
    void *_Nullable *_Nonnull vret_decoded,
    uint7b_t opcode,
    void (*_Nullable *_Nonnull ret_execution_handler)(
        struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins))
{
    assert(vret_decoded);

    struct decoded_rv64_base_ins_r **ret_decoded =
        (struct decoded_rv64_base_ins_r **)vret_decoded;

    if(!(*ret_decoded)) {
        *ret_decoded = malloc(sizeof(struct decoded_rv64_base_ins_r));
    }
    if(!(*ret_decoded)) {
        return ENOMEM;
    }

    (*ret_decoded)->opcode = opcode;
    (*ret_decoded)->rd     = decode_rd(ins);
    (*ret_decoded)->rs1    = decode_rs1(ins);
    (*ret_decoded)->rs2    = decode_rs2(ins);
    (*ret_decoded)->func3  = decode_func3(ins);
    (*ret_decoded)->func7  = decode_func7(ins);

    *ret_execution_handler =
        execution_handlers[(*ret_decoded)->opcode][(*ret_decoded)->func3]
                          [(*ret_decoded)->func7];

    return 0;
}
int decode_ins_i(
    rv64_instruction_t ins,
    void *_Nullable *_Nonnull vret_decoded,
    uint7b_t opcode,
    void (*_Nullable *_Nonnull ret_execution_handler)(
        struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins))
{
    assert(vret_decoded);

    struct decoded_rv64_base_ins_i **ret_decoded =
        (struct decoded_rv64_base_ins_i **)vret_decoded;

    if(!(*ret_decoded)) {
        *ret_decoded = malloc(sizeof(struct decoded_rv64_base_ins_i));
    }
    if(!(*ret_decoded)) {
        return ENOMEM;
    }

    (*ret_decoded)->opcode = opcode;
    (*ret_decoded)->rd     = decode_rd(ins);
    (*ret_decoded)->rs1    = decode_rs1(ins);
    (*ret_decoded)->func3  = decode_func3(ins);
    (*ret_decoded)->imm    = decode_imm_i(ins);

    // HACK: since the z axis is don't care, use the value of the func7 position, since shift right instructions use that as shift type
    //  as a result, right shift handlers are correctly selected, and other instructions indexes were don't care in the first place
    //  we need to clear the least significant bit because the shamt field extends to the least significant bit of func7
    uint8_t hack_func7 = decode_func7(ins);
    hack_func7 >>= 1;
    hack_func7 <<= 1;
    *ret_execution_handler =
        execution_handlers[(*ret_decoded)->opcode][(*ret_decoded)->func3]
                          [hack_func7];

    return 0;
}
int decode_ins_s(
    rv64_instruction_t ins,
    void *_Nullable *_Nonnull vret_decoded,
    uint7b_t opcode,
    void (*_Nullable *_Nonnull ret_execution_handler)(
        struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins))
{
    assert(vret_decoded);

    struct decoded_rv64_base_ins_s **ret_decoded =
        (struct decoded_rv64_base_ins_s **)vret_decoded;

    if(!(*ret_decoded)) {
        *ret_decoded = malloc(sizeof(struct decoded_rv64_base_ins_s));
    }
    if(!(*ret_decoded)) {
        return ENOMEM;
    }

    (*ret_decoded)->opcode = opcode;
    (*ret_decoded)->rs1    = decode_rs1(ins);
    (*ret_decoded)->rs2    = decode_rs2(ins);
    (*ret_decoded)->func3  = decode_func3(ins);
    (*ret_decoded)->imm    = decode_imm_s(ins);

    *ret_execution_handler =
        execution_handlers[(*ret_decoded)->opcode][(*ret_decoded)->func3]
                          [EXECUTION_HANDLER_INX_DONTCARE];

    return 0;
}
int decode_ins_b(
    rv64_instruction_t ins,
    void *_Nullable *_Nonnull vret_decoded,
    uint7b_t opcode,
    void (*_Nullable *_Nonnull ret_execution_handler)(
        struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins))
{
    assert(vret_decoded);

    struct decoded_rv64_base_ins_b **ret_decoded =
        (struct decoded_rv64_base_ins_b **)vret_decoded;

    if(!(*ret_decoded)) {
        *ret_decoded = malloc(sizeof(struct decoded_rv64_base_ins_b));
    }
    if(!(*ret_decoded)) {
        return ENOMEM;
    }

    (*ret_decoded)->opcode = opcode;
    (*ret_decoded)->rs1    = decode_rs1(ins);
    (*ret_decoded)->rs2    = decode_rs2(ins);
    (*ret_decoded)->func3  = decode_func3(ins);
    (*ret_decoded)->imm    = decode_imm_b(ins);

    *ret_execution_handler =
        execution_handlers[(*ret_decoded)->opcode][(*ret_decoded)->func3]
                          [EXECUTION_HANDLER_INX_DONTCARE];

    return 0;
}
int decode_ins_u(
    rv64_instruction_t ins,
    void *_Nullable *_Nonnull vret_decoded,
    uint7b_t opcode,
    void (*_Nullable *_Nonnull ret_execution_handler)(
        struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins))
{
    assert(vret_decoded);

    struct decoded_rv64_base_ins_u **ret_decoded =
        (struct decoded_rv64_base_ins_u **)vret_decoded;

    if(!(*ret_decoded)) {
        *ret_decoded = malloc(sizeof(struct decoded_rv64_base_ins_u));
    }
    if(!(*ret_decoded)) {
        return ENOMEM;
    }

    (*ret_decoded)->opcode = opcode;
    (*ret_decoded)->rd     = decode_rd(ins);
    (*ret_decoded)->imm    = decode_imm_u(ins);

    *ret_execution_handler = execution_handlers[(*ret_decoded)->opcode]
                                               [EXECUTION_HANDLER_INX_DONTCARE]
                                               [EXECUTION_HANDLER_INX_DONTCARE];

    return 0;
}
int decode_ins_j(
    rv64_instruction_t ins,
    void *_Nullable *_Nonnull vret_decoded,
    uint7b_t opcode,
    void (*_Nullable *_Nonnull ret_execution_handler)(
        struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins))
{
    assert(vret_decoded);

    struct decoded_rv64_base_ins_j **ret_decoded =
        (struct decoded_rv64_base_ins_j **)vret_decoded;

    if(!(*ret_decoded)) {
        *ret_decoded = malloc(sizeof(struct decoded_rv64_base_ins_j));
    }
    if(!(*ret_decoded)) {
        return ENOMEM;
    }

    (*ret_decoded)->opcode = opcode;
    (*ret_decoded)->rd     = decode_rd(ins);
    (*ret_decoded)->imm    = decode_imm_j(ins);

    *ret_execution_handler = execution_handlers[(*ret_decoded)->opcode]
                                               [EXECUTION_HANDLER_INX_DONTCARE]
                                               [EXECUTION_HANDLER_INX_DONTCARE];

    return 0;
}

void free_rv64_cpu(struct rv64_cpu *_Nonnull cpu)
{
    assert(cpu);

    free(cpu->regs);
    cpu->regs = NULL;
    free(cpu->mem);
    cpu->mem = NULL;
}

int init_rv64_cpu(struct rv64_cpu *_Nonnull cpu, struct cpu_opt *_Nullable opt)
{
    assert(cpu);

    cpu->opt.mem_size = BASE_MEM_SIZE;
    cpu->opt.regs     = BASE_REGS_NUM;

    if(opt) {
        cpu->opt = *opt;
    }

    cpu->regs = calloc(1, sizeof(uint64_t) * cpu->opt.regs);
    if(!cpu->regs) {
        return ENOMEM;
    }

    cpu->mem = calloc(1, cpu->opt.mem_size);
    if(!cpu->mem) {
        return ENOMEM;
    }

    cpu->i_flags.pc_updated = 0;

    return 0;
}

void step_rv64_cpu(struct rv64_cpu *_Nonnull cpu)
{
    assert(cpu);

    rv64_instruction_t current_instruction = 0;
    uint8_t opcode                         = 0;
    void *decoded_ins                      = NULL;
    void (*execution_handler)(
        struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins);
    fetch(cpu, &current_instruction);

    opcode = decode_opcode(current_instruction);

    ins_decode_handlers[opcode](
        current_instruction, &decoded_ins, opcode, &execution_handler);

    execution_handler(cpu, &decoded_ins);

    advance_pc_or_update_i_flags(cpu);
}

void mainloop_rv64_cpu(struct rv64_cpu *_Nonnull cpu)
{
    assert(cpu);

    rv64_instruction_t next_ins = 0;

    while(1) {
        step_rv64_cpu(cpu);
        fetch(cpu, &next_ins);
        if(next_ins == HALT_MAGIC) {
            break;
        }
    }
}

void execute_addi(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_i)
{
    assert(cpu);
    assert(vdecoded_ins_i);
    assert(*vdecoded_ins_i);

    _cleanup_free_ struct decoded_rv64_base_ins_i *decoded_ins =
        MOVE(vdecoded_ins_i);

    cpu->regs[decoded_ins->rd] = cpu->regs[decoded_ins->rs1] + decoded_ins->imm;
}

void execute_addiw(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_i)
{
    assert(cpu);
    assert(vdecoded_ins_i);
    assert(*vdecoded_ins_i);

    _cleanup_free_ struct decoded_rv64_base_ins_i *decoded_ins =
        MOVE(vdecoded_ins_i);

    uint32_t rs1_lower = cpu->regs[decoded_ins->rs1];
    rs1_lower += (uint32_t)decoded_ins->imm;

    cpu->regs[decoded_ins->rd] = sign_extend_u32_to_u64(rs1_lower);
}

void execute_slti(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_i)
{
    assert(cpu);
    assert(vdecoded_ins_i);
    assert(*vdecoded_ins_i);

    _cleanup_free_ struct decoded_rv64_base_ins_i *decoded_ins =
        MOVE(vdecoded_ins_i);

    cpu->regs[decoded_ins->rd] =
        (int64_t)cpu->regs[decoded_ins->rs1] < (int64_t)decoded_ins->imm ? 1
                                                                         : 0;
}

void execute_sltiu(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_i)
{
    assert(cpu);
    assert(vdecoded_ins_i);
    assert(*vdecoded_ins_i);

    _cleanup_free_ struct decoded_rv64_base_ins_i *decoded_ins =
        MOVE(vdecoded_ins_i);

    cpu->regs[decoded_ins->rd] =
        cpu->regs[decoded_ins->rs1] < decoded_ins->imm ? 1 : 0;
}

void execute_andi(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_i)
{
    assert(cpu);
    assert(vdecoded_ins_i);
    assert(*vdecoded_ins_i);

    _cleanup_free_ struct decoded_rv64_base_ins_i *decoded_ins =
        MOVE(vdecoded_ins_i);

    cpu->regs[decoded_ins->rd] = cpu->regs[decoded_ins->rs1] & decoded_ins->imm;
}

void execute_ori(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_i)
{
    assert(cpu);
    assert(vdecoded_ins_i);
    assert(*vdecoded_ins_i);

    _cleanup_free_ struct decoded_rv64_base_ins_i *decoded_ins =
        MOVE(vdecoded_ins_i);

    cpu->regs[decoded_ins->rd] = cpu->regs[decoded_ins->rs1] | decoded_ins->imm;
}

void execute_xori(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_i)

{
    assert(cpu);
    assert(vdecoded_ins_i);
    assert(*vdecoded_ins_i);

    _cleanup_free_ struct decoded_rv64_base_ins_i *decoded_ins =
        MOVE(vdecoded_ins_i);

    cpu->regs[decoded_ins->rd] = cpu->regs[decoded_ins->rs1] ^ decoded_ins->imm;
}

void execute_slli(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_i)
{
    assert(cpu);
    assert(vdecoded_ins_i);
    assert(*vdecoded_ins_i);

    _cleanup_free_ struct decoded_rv64_base_ins_i *decoded_ins =
        MOVE(vdecoded_ins_i);
    uint8_t shamt =
        decoded_ins->imm & bitmask_from_bit_size(SHIFT_SHAMT_BIT_SIZE);

    cpu->regs[decoded_ins->rd] = cpu->regs[decoded_ins->rs1] << shamt;
}
void execute_slliw(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_i)
{
    assert(cpu);
    assert(vdecoded_ins_i);
    assert(*vdecoded_ins_i);

    _cleanup_free_ struct decoded_rv64_base_ins_i *decoded_ins =
        MOVE(vdecoded_ins_i);
    uint8_t shamt =
        decoded_ins->imm & bitmask_from_bit_size(SHIFTW_SHAMT_BIT_SIZE);
    uint32_t rs1_lower = ((uint32_t)cpu->regs[decoded_ins->rs1]);
    uint8_t sign_bit   = GET_SIGN_BIT(rs1_lower);

    cpu->regs[decoded_ins->rd] = sign_extend_u32_to_u64(rs1_lower << shamt);
}

void execute_srlai(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_i)
{
    assert(cpu);
    assert(vdecoded_ins_i);
    assert(*vdecoded_ins_i);

    _cleanup_free_ struct decoded_rv64_base_ins_i *decoded_ins =
        MOVE(vdecoded_ins_i);

    uint64_t shift_type_bit_mask = 1 << SHIFT_RIGHT_TYPE_BIT_POS_IN_IMM;
    uint8_t do_arithmatic_shift =
        decoded_ins->imm & shift_type_bit_mask ? 1 : 0;

    if(do_arithmatic_shift) {
        execute_srai(cpu, decoded_ins);
    } else {
        execute_srli(cpu, decoded_ins);
    }
}

void execute_srli(
    struct rv64_cpu *_Nonnull cpu,
    struct decoded_rv64_base_ins_i *_Nonnull decoded_ins)
{
    uint8_t shamt =
        decoded_ins->imm & bitmask_from_bit_size(SHIFT_SHAMT_BIT_SIZE);
    cpu->regs[decoded_ins->rd] = cpu->regs[decoded_ins->rs1] >> shamt;
}

void execute_srai(
    struct rv64_cpu *_Nonnull cpu,
    struct decoded_rv64_base_ins_i *_Nonnull decoded_ins)
{
    uint8_t shamt =
        decoded_ins->imm & bitmask_from_bit_size(SHIFT_SHAMT_BIT_SIZE);

    uint64_t sign_bit =
        ((uint64_t)1 << (XLEN - 1)) & cpu->regs[decoded_ins->rs1];

    cpu->regs[decoded_ins->rd] = cpu->regs[decoded_ins->rs1];
    for(int i = 0; i < shamt; i++) {
        cpu->regs[decoded_ins->rd] = cpu->regs[decoded_ins->rd] >> 1;
        cpu->regs[decoded_ins->rd] |= sign_bit;
    }
}

void execute_srlaiw(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_i)
{
    assert(cpu);
    assert(vdecoded_ins_i);
    assert(*vdecoded_ins_i);

    _cleanup_free_ struct decoded_rv64_base_ins_i *decoded_ins =
        MOVE(vdecoded_ins_i);

    uint64_t shift_type_bit_mask = 1 << SHIFTW_RIGHT_TYPE_BIT_POS_IN_IMM;
    uint8_t do_arithmatic_shift =
        decoded_ins->imm & shift_type_bit_mask ? 1 : 0;

    if(do_arithmatic_shift) {
        execute_sraiw(cpu, decoded_ins);
    } else {
        execute_srliw(cpu, decoded_ins);
    }
}

void execute_srliw(
    struct rv64_cpu *_Nonnull cpu,
    struct decoded_rv64_base_ins_i *_Nonnull decoded_ins)
{
    uint8_t shamt =
        decoded_ins->imm & bitmask_from_bit_size(SHIFTW_SHAMT_BIT_SIZE);
    uint32_t lower_rs1         = cpu->regs[decoded_ins->rs1];
    cpu->regs[decoded_ins->rd] = sign_extend_u32_to_u64(lower_rs1 >> shamt);
}

void execute_sraiw(
    struct rv64_cpu *_Nonnull cpu,
    struct decoded_rv64_base_ins_i *_Nonnull decoded_ins)
{
    uint8_t shamt =
        decoded_ins->imm & bitmask_from_bit_size(SHIFTW_SHAMT_BIT_SIZE);

    uint32_t lower_rs1 = cpu->regs[decoded_ins->rs1];
    uint32_t sign_bit  = GET_SIGN_BIT(lower_rs1) << ((XLEN / 2) - 1);

    for(int i = 0; i < shamt; i++) {
        lower_rs1 = lower_rs1 >> 1;
        lower_rs1 |= sign_bit;
    }

    cpu->regs[decoded_ins->rd] = sign_extend_u32_to_u64(lower_rs1);
}

void execute_lui(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_u)
{
    assert(cpu);
    assert(vdecoded_ins_u);
    assert(*vdecoded_ins_u);

    _cleanup_free_ struct decoded_rv64_base_ins_u *decoded_ins =
        MOVE(vdecoded_ins_u);

    cpu->regs[decoded_ins->rd] = decoded_ins->imm;
}

void execute_auipc(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_u)
{
    assert(cpu);
    assert(vdecoded_ins_u);
    assert(*vdecoded_ins_u);

    _cleanup_free_ struct decoded_rv64_base_ins_u *decoded_ins =
        MOVE(vdecoded_ins_u);

    cpu->regs[decoded_ins->rd] = decoded_ins->imm + cpu->regs[REG_INX_PC];
}

void execute_add(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_r)
{
    assert(cpu);
    assert(vdecoded_ins_r);
    assert(*vdecoded_ins_r);

    _cleanup_free_ struct decoded_rv64_base_ins_r *decoded_ins =
        MOVE(vdecoded_ins_r);

    cpu->regs[decoded_ins->rd] =
        cpu->regs[decoded_ins->rs1] + cpu->regs[decoded_ins->rs2];
}

void execute_sub(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_r)
{
    assert(cpu);
    assert(vdecoded_ins_r);
    assert(*vdecoded_ins_r);

    _cleanup_free_ struct decoded_rv64_base_ins_r *decoded_ins =
        MOVE(vdecoded_ins_r);

    cpu->regs[decoded_ins->rd] =
        cpu->regs[decoded_ins->rs1] - cpu->regs[decoded_ins->rs2];
}

void execute_slt(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_r)
{
    assert(cpu);
    assert(vdecoded_ins_r);
    assert(*vdecoded_ins_r);

    _cleanup_free_ struct decoded_rv64_base_ins_r *decoded_ins =
        MOVE(vdecoded_ins_r);

    cpu->regs[decoded_ins->rd] = (int64_t)cpu->regs[decoded_ins->rs1] <
                                         (int64_t)cpu->regs[decoded_ins->rs2]
                                     ? 1
                                     : 0;
}

void execute_sltu(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_r)
{
    assert(cpu);
    assert(vdecoded_ins_r);
    assert(*vdecoded_ins_r);

    _cleanup_free_ struct decoded_rv64_base_ins_r *decoded_ins =
        MOVE(vdecoded_ins_r);

    cpu->regs[decoded_ins->rd] =
        cpu->regs[decoded_ins->rs1] < cpu->regs[decoded_ins->rs2] ? 1 : 0;
}

void execute_and(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_r)
{
    assert(cpu);
    assert(vdecoded_ins_r);
    assert(*vdecoded_ins_r);

    _cleanup_free_ struct decoded_rv64_base_ins_r *decoded_ins =
        MOVE(vdecoded_ins_r);

    cpu->regs[decoded_ins->rd] =
        cpu->regs[decoded_ins->rs1] & cpu->regs[decoded_ins->rs2];
}

void execute_or(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_r)
{
    assert(cpu);
    assert(vdecoded_ins_r);
    assert(*vdecoded_ins_r);

    _cleanup_free_ struct decoded_rv64_base_ins_r *decoded_ins =
        MOVE(vdecoded_ins_r);

    cpu->regs[decoded_ins->rd] =
        cpu->regs[decoded_ins->rs1] | cpu->regs[decoded_ins->rs2];
}

void execute_xor(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_r)
{
    assert(cpu);
    assert(vdecoded_ins_r);
    assert(*vdecoded_ins_r);

    _cleanup_free_ struct decoded_rv64_base_ins_r *decoded_ins =
        MOVE(vdecoded_ins_r);

    cpu->regs[decoded_ins->rd] =
        cpu->regs[decoded_ins->rs1] ^ cpu->regs[decoded_ins->rs2];
}

void execute_jal(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_j)
{
    assert(cpu);
    assert(vdecoded_ins_j);
    assert(*vdecoded_ins_j);

    _cleanup_free_ struct decoded_rv64_base_ins_j *decoded_ins =
        MOVE(vdecoded_ins_j);

    cpu->regs[decoded_ins->rd] = cpu->regs[REG_INX_PC] + 4;
    cpu->regs[REG_INX_PC] += decoded_ins->imm;
    cpu->i_flags.pc_updated = 1;
}

void execute_jalr(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_i)
{
    assert(cpu);
    assert(vdecoded_ins_i);
    assert(*vdecoded_ins_i);

    _cleanup_free_ struct decoded_rv64_base_ins_i *decoded_ins =
        MOVE(vdecoded_ins_i);

    cpu->regs[decoded_ins->rd] = cpu->regs[REG_INX_PC] + 4;

    cpu->regs[REG_INX_PC] = (cpu->regs[decoded_ins->rs1] + decoded_ins->imm);

    cpu->regs[REG_INX_PC] >>= 1;
    cpu->regs[REG_INX_PC] <<= 1;

    cpu->i_flags.pc_updated = 1;
}

void execute_sll(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_r)
{
    assert(cpu);
    assert(vdecoded_ins_r);
    assert(*vdecoded_ins_r);

    _cleanup_free_ struct decoded_rv64_base_ins_r *decoded_ins =
        MOVE(vdecoded_ins_r);
    uint8_t shamt = cpu->regs[decoded_ins->rs2] &
                    bitmask_from_bit_size(SHIFT_SHAMT_BIT_SIZE);

    cpu->regs[decoded_ins->rd] = cpu->regs[decoded_ins->rs1] << shamt;
}

void execute_srla(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_r)
{
    assert(cpu);
    assert(vdecoded_ins_r);
    assert(*vdecoded_ins_r);

    _cleanup_free_ struct decoded_rv64_base_ins_r *decoded_ins =
        MOVE(vdecoded_ins_r);

    uint64_t shift_type_bit_mask = 1 << SHIFT_RIGHT_TYPE_BIT_POS_IN_FUNC7;
    uint8_t do_arithmatic_shift =
        decoded_ins->func7 & shift_type_bit_mask ? 1 : 0;

    if(do_arithmatic_shift) {
        execute_sra(cpu, decoded_ins);
    } else {
        execute_srl(cpu, decoded_ins);
    }
}

void execute_srl(
    struct rv64_cpu *_Nonnull cpu,
    struct decoded_rv64_base_ins_r *_Nonnull decoded_ins)
{
    uint8_t shamt              = cpu->regs[decoded_ins->rs2] &
                                 bitmask_from_bit_size(SHIFT_SHAMT_BIT_SIZE);
    cpu->regs[decoded_ins->rd] = cpu->regs[decoded_ins->rs1] >> shamt;
}

void execute_sra(
    struct rv64_cpu *_Nonnull cpu,
    struct decoded_rv64_base_ins_r *_Nonnull decoded_ins)
{
    uint8_t shamt = cpu->regs[decoded_ins->rs2] &
                    bitmask_from_bit_size(SHIFT_SHAMT_BIT_SIZE);

    uint64_t sign_bit = GET_SIGN_BIT(cpu->regs[decoded_ins->rs1]) << (XLEN - 1);

    cpu->regs[decoded_ins->rd] = cpu->regs[decoded_ins->rs1];
    for(int i = 0; i < shamt; i++) {
        cpu->regs[decoded_ins->rd] = cpu->regs[decoded_ins->rd] >> 1;
        cpu->regs[decoded_ins->rd] |= sign_bit;
    }
}

void execute_addw(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_r)
{
    assert(cpu);
    assert(vdecoded_ins_r);
    assert(*vdecoded_ins_r);

    _cleanup_free_ struct decoded_rv64_base_ins_r *decoded_ins =
        MOVE(vdecoded_ins_r);
    uint32_t lower_rs1 = cpu->regs[decoded_ins->rs1];
    uint32_t lower_rs2 = cpu->regs[decoded_ins->rs2];

    cpu->regs[decoded_ins->rd] = sign_extend_u32_to_u64(lower_rs1 + lower_rs2);
}

void execute_sllw(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_r)
{
    assert(cpu);
    assert(vdecoded_ins_r);
    assert(*vdecoded_ins_r);

    _cleanup_free_ struct decoded_rv64_base_ins_r *decoded_ins =
        MOVE(vdecoded_ins_r);
    uint8_t shamt      = cpu->regs[decoded_ins->rs2] &
                         bitmask_from_bit_size(SHIFTW_SHAMT_BIT_SIZE);
    uint32_t lower_rs1 = cpu->regs[decoded_ins->rs1];

    cpu->regs[decoded_ins->rd] = sign_extend_u32_to_u64(lower_rs1 << shamt);
}

void execute_srlaw(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_r)
{
    assert(cpu);
    assert(vdecoded_ins_r);
    assert(*vdecoded_ins_r);

    _cleanup_free_ struct decoded_rv64_base_ins_r *decoded_ins =
        MOVE(vdecoded_ins_r);

    uint64_t shift_type_bit_mask = 1 << SHIFT_RIGHT_TYPE_BIT_POS_IN_FUNC7;
    uint8_t do_arithmatic_shift =
        decoded_ins->func7 & shift_type_bit_mask ? 1 : 0;

    if(do_arithmatic_shift) {
        execute_sraw(cpu, decoded_ins);
    } else {
        execute_srlw(cpu, decoded_ins);
    }
}

void execute_srlw(
    struct rv64_cpu *_Nonnull cpu,
    struct decoded_rv64_base_ins_r *_Nonnull decoded_ins)
{
    uint8_t shamt              = cpu->regs[decoded_ins->rs2] &
                                 bitmask_from_bit_size(SHIFTW_SHAMT_BIT_SIZE);
    uint32_t lower_rs1         = cpu->regs[decoded_ins->rs1];
    cpu->regs[decoded_ins->rd] = sign_extend_u32_to_u64(lower_rs1 >> shamt);
}

void execute_sraw(
    struct rv64_cpu *_Nonnull cpu,
    struct decoded_rv64_base_ins_r *_Nonnull decoded_ins)
{
    uint8_t shamt = cpu->regs[decoded_ins->rs2] &
                    bitmask_from_bit_size(SHIFTW_SHAMT_BIT_SIZE);

    uint32_t lower_rs1 = cpu->regs[decoded_ins->rs1];
    uint32_t sign_bit  = GET_SIGN_BIT(lower_rs1) << ((XLEN / 2) - 1);

    for(int i = 0; i < shamt; i++) {
        lower_rs1 = lower_rs1 >> 1;
        lower_rs1 |= sign_bit;
    }

    cpu->regs[decoded_ins->rd] = sign_extend_u32_to_u64(lower_rs1);
}

void execute_subw(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_r)
{
    assert(cpu);
    assert(vdecoded_ins_r);
    assert(*vdecoded_ins_r);

    _cleanup_free_ struct decoded_rv64_base_ins_r *decoded_ins =
        MOVE(vdecoded_ins_r);
    uint32_t lower_rs1 = cpu->regs[decoded_ins->rs1];
    uint32_t lower_rs2 = cpu->regs[decoded_ins->rs2];

    cpu->regs[decoded_ins->rd] = sign_extend_u32_to_u64(lower_rs1 - lower_rs2);
}

/** TODO: rv64 unprivileged 2.5: The conditional branch instructions will generate an instruction-address-misaligned exception if the
 *  target address is not aligned to a four-byte boundary and the branch condition evaluates to true. If the
 *  branch condition evaluates to false, the instruction-address-misaligned exception will not be raised.
 */
void execute_beq(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_b)
{
    assert(cpu);
    assert(vdecoded_ins_b);
    assert(*vdecoded_ins_b);

    _cleanup_free_ struct decoded_rv64_base_ins_b *decoded_ins =
        MOVE(vdecoded_ins_b);

    if(cpu->regs[decoded_ins->rs1] == cpu->regs[decoded_ins->rs2]) {
        cpu->regs[REG_INX_PC] += decoded_ins->imm;
        cpu->i_flags.pc_updated = 1;
    }
}

void execute_bne(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_b)
{
    assert(cpu);
    assert(vdecoded_ins_b);
    assert(*vdecoded_ins_b);

    _cleanup_free_ struct decoded_rv64_base_ins_b *decoded_ins =
        MOVE(vdecoded_ins_b);

    if(cpu->regs[decoded_ins->rs1] != cpu->regs[decoded_ins->rs2]) {
        cpu->regs[REG_INX_PC] += decoded_ins->imm;
        cpu->i_flags.pc_updated = 1;
    }
}

void execute_blt(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_b)
{
    assert(cpu);
    assert(vdecoded_ins_b);
    assert(*vdecoded_ins_b);

    _cleanup_free_ struct decoded_rv64_base_ins_b *decoded_ins =
        MOVE(vdecoded_ins_b);

    if((int64_t)cpu->regs[decoded_ins->rs1] <
       (int64_t)cpu->regs[decoded_ins->rs2]) {
        cpu->regs[REG_INX_PC] += decoded_ins->imm;
        cpu->i_flags.pc_updated = 1;
    }
}

void execute_bltu(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_b)
{
    assert(cpu);
    assert(vdecoded_ins_b);
    assert(*vdecoded_ins_b);

    _cleanup_free_ struct decoded_rv64_base_ins_b *decoded_ins =
        MOVE(vdecoded_ins_b);

    if(cpu->regs[decoded_ins->rs1] < cpu->regs[decoded_ins->rs2]) {
        cpu->regs[REG_INX_PC] += decoded_ins->imm;
        cpu->i_flags.pc_updated = 1;
    }
}

void execute_bge(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_b)
{
    assert(cpu);
    assert(vdecoded_ins_b);
    assert(*vdecoded_ins_b);

    _cleanup_free_ struct decoded_rv64_base_ins_b *decoded_ins =
        MOVE(vdecoded_ins_b);

    if((int64_t)cpu->regs[decoded_ins->rs1] >=
       (int64_t)cpu->regs[decoded_ins->rs2]) {
        cpu->regs[REG_INX_PC] += decoded_ins->imm;
        cpu->i_flags.pc_updated = 1;
    }
}
void execute_bgeu(
    struct rv64_cpu *_Nonnull cpu, void *_Nonnull *_Nonnull vdecoded_ins_b)
{
    assert(cpu);
    assert(vdecoded_ins_b);
    assert(*vdecoded_ins_b);

    _cleanup_free_ struct decoded_rv64_base_ins_b *decoded_ins =
        MOVE(vdecoded_ins_b);

    if(cpu->regs[decoded_ins->rs1] >= cpu->regs[decoded_ins->rs2]) {
        cpu->regs[REG_INX_PC] += decoded_ins->imm;
        cpu->i_flags.pc_updated = 1;
    }
}

int read_mem(
    struct rv64_cpu *_Nonnull cpu,
    uint64_t address,
    uint64_t *_Nonnull ret,
    uint64_t length)
{
    assert(ret);
    assert(cpu);

    assert(length <= 8);

    uint64_t current_fetch = 0;

    (*ret) = 0;

    for(int i = 0; i < length; i++) {
        current_fetch = cpu->mem[(address + i) % (cpu->opt.mem_size)];
        // NOLINTNEXTLINE(readability-magic-numbers)
        current_fetch <<= (i * 8);
        *ret |= current_fetch;
    }

    return 0;
}

int read_mem8(
    struct rv64_cpu *_Nonnull cpu, uint64_t address, uint8_t *_Nonnull ret)
{
    return INTERNAL_MEM_READ_UINT_TYPED(cpu, address, ret);
}

int read_mem16(
    struct rv64_cpu *_Nonnull cpu, uint64_t address, uint16_t *_Nonnull ret)
{
    return INTERNAL_MEM_READ_UINT_TYPED(cpu, address, ret);
}

int read_mem32(
    struct rv64_cpu *_Nonnull cpu, uint64_t address, uint32_t *_Nonnull ret)
{
    return INTERNAL_MEM_READ_UINT_TYPED(cpu, address, ret);
}

int read_mem64(
    struct rv64_cpu *_Nonnull cpu, uint64_t address, uint64_t *_Nonnull ret)
{
    return INTERNAL_MEM_READ_UINT_TYPED(cpu, address, ret);
}

// NOLINTNEXTLINE(bugprone-easily-swappable-parameters)
int write_mem(
    struct rv64_cpu *_Nonnull cpu,
    uint64_t address,
    uint64_t length,
    uint64_t write)
{
    assert(cpu);

    assert(length <= 8);

    uint64_t current_fetch = 0;

    for(int i = 0; i < length; i++) {
        // NOLINTNEXTLINE(readability-magic-numbers)
        cpu->mem[(address + i) % (cpu->opt.mem_size)] = write & 0xff;
        // NOLINTNEXTLINE(readability-magic-numbers)
        write >>= 8;
    }

    return 0;
}

int write_mem8(struct rv64_cpu *_Nonnull cpu, uint64_t address, uint8_t write)
{
    return INTERNAL_MEM_WRITE_UINT_TYPED(cpu, address, write);
}

int write_mem16(struct rv64_cpu *_Nonnull cpu, uint64_t address, uint16_t write)
{
    return INTERNAL_MEM_WRITE_UINT_TYPED(cpu, address, write);
}

int write_mem32(struct rv64_cpu *_Nonnull cpu, uint64_t address, uint32_t write)
{
    return INTERNAL_MEM_WRITE_UINT_TYPED(cpu, address, write);
}

int write_mem64(struct rv64_cpu *_Nonnull cpu, uint64_t address, uint64_t write)
{
    return INTERNAL_MEM_WRITE_UINT_TYPED(cpu, address, write);
}

int fetch(struct rv64_cpu *_Nonnull cpu, rv64_instruction_t *_Nonnull ret_ins)
{
    int err = 0;

    err = read_mem32(cpu, cpu->regs[REG_INX_PC], ret_ins);

    return err;
}

void advance_pc_or_update_i_flags(struct rv64_cpu *_Nonnull cpu)
{
    if(cpu->i_flags.pc_updated) {
        cpu->i_flags.pc_updated = 0;
        return;
    }
    cpu->regs[REG_INX_PC] += sizeof(rv64_instruction_t);
}

void fill_execution_handler_with_default_handler()
{

    for(int i = 0; i < OPCODE_MAX + 1; i++) {

        for(int j = 0; j < FUNC3_MAX + 1; j++) {

            for(int k = 0; k < FUNC7_MAX + 1; k++) {

                execution_handlers[i][j][k] = illegal_instruction_handler;
            }
        }
    }
}

void register_execution_handler(
    uint8_t opcode,
    const int *_Nullable func7,
    const int *_Nullable func3,
    void (*handler)(struct rv64_cpu *_Nonnull, void *_Nonnull *_Nonnull))
{
    uint8_t func7_start = 0;
    uint8_t func7_end   = FUNC7_MAX + 1;
    uint8_t func3_start = 0;
    uint8_t func3_end   = FUNC3_MAX + 1;

    if(func3) {
        assert(*func3 <= FUNC3_MAX);

        func3_start = *func3;
        func3_end   = func3_start + 1;
    }

    if(func7) {
        assert(*func7 <= FUNC7_MAX);

        func7_start = *func7;
        func7_end   = func7_start + 1;
    }

    for(int i = func3_start; i < func3_end; i++) {
        for(int j = func7_start; j < func7_end; j++) {
            execution_handlers[opcode][i][j] = handler;
        }
    }
}
